// =============================================================================
// agentic/run_logger.js
//
// Records every LLM call made during a bot run (system prompt, user prompt,
// model, response, kind, phase, duration) and writes two files per run:
//
//   bot/logs/runs/run_<ISO>.json   -- the authoritative per-run log
//   bot/logs/runs/latest.js        -- `window.RUN = {...};` for dashboard.html
//
// The dashboard at bot/dashboard.html reads latest.js via a <script> tag so it
// works from file:// without an HTTP server.
//
// Public API:
//   run_logger.init({ communities, dryRun, model, ... }) -- call once at boot.
//   run_logger.recordCall({ label, model, kind, phase, system, user, response, durationMs })
//   run_logger.beginCycle(n, communityUrl, communityName)
// =============================================================================

"use strict";

const fs   = require("fs");
const path = require("path");

const LOGS_DIR    = path.join(__dirname, "..", "logs", "runs");
const LATEST_JS   = path.join(LOGS_DIR, "latest.js");

var STATE = {
    initialized: false,
    runFile:     null,
    run: {
        startedAt:   null,
        env:         {},
        cycles:      [],   // [{ n, startedAt, communityUrl, communityName, calls: [] }]
        calls:       [],   // mirror of all calls, for dashboard convenience
    },
    currentCycle: null,
};

function ensureDir() {
    try { fs.mkdirSync(LOGS_DIR, { recursive: true }); } catch (_) {}
}

function safeWriteAtomic(file, body) {
    try {
        var tmp = file + ".tmp";
        fs.writeFileSync(tmp, body);
        fs.renameSync(tmp, file);
    } catch (e) {
        // We never want logging to crash the bot.
        try { console.warn("[run_logger] write failed for " + file + ": " + e.message); } catch (_) {}
    }
}

function flush() {
    if (!STATE.initialized || !STATE.runFile) return;
    safeWriteAtomic(STATE.runFile, JSON.stringify(STATE.run, null, 2));
    // Dashboard loader: assigns the run JSON to window.RUN. Single script tag,
    // no CORS, works straight from file:// when the dashboard is opened with
    // a double-click.
    var js = "// auto-generated by bot/agentic/run_logger.js  (last update: "
        + new Date().toISOString() + ")\n"
        + "window.RUN = " + JSON.stringify(STATE.run) + ";\n";
    safeWriteAtomic(LATEST_JS, js);
}

function init(meta) {
    if (STATE.initialized) return STATE.runFile;
    ensureDir();
    var ts = new Date().toISOString().replace(/[:.]/g, "-");
    STATE.runFile = path.join(LOGS_DIR, "run_" + ts + ".json");
    STATE.run.startedAt = new Date().toISOString();
    STATE.run.env = meta || {};
    STATE.initialized = true;
    flush();
    console.log("[run_logger] logging to " + STATE.runFile);
    return STATE.runFile;
}

function beginCycle(n, communityUrl, communityName) {
    if (!STATE.initialized) init({});
    STATE.currentCycle = {
        n:             n,
        startedAt:     new Date().toISOString(),
        communityUrl:  communityUrl || "",
        communityName: communityName || "",
        calls:         [],
    };
    STATE.run.cycles.push(STATE.currentCycle);
    flush();
}

function recordCall(call) {
    if (!STATE.initialized) init({});
    var entry = {
        ts:         new Date().toISOString(),
        label:      call.label  || "",
        model:      call.model  || "",
        kind:       call.kind   || "writer",  // "picker" | "writer"
        phase:      call.phase  || "?",       // "A" | "B" | "RAG" | ...
        cycle:      STATE.currentCycle ? STATE.currentCycle.n : null,
        system:     call.system || "",
        user:       call.user   || "",
        response:   (typeof call.response === "string")
                        ? call.response
                        : (call.response != null ? JSON.parse(JSON.stringify(call.response)) : null),
        durationMs: typeof call.durationMs === "number" ? call.durationMs : null,
    };
    STATE.run.calls.push(entry);
    if (STATE.currentCycle) STATE.currentCycle.calls.push(entry);
    flush();
}

module.exports = {
    init,
    beginCycle,
    recordCall,
    // Exposed for debugging only.
    _state: STATE,
};
